In [1]:
import pandas as pd


In [2]:
results_V01 = pd.read_csv(
    "results/v0.1_baseline_ragas_results.csv"
)

display(
    results_V01[["case_id", "faithfulness", "context_precision", "response_relevancy", "factual_correctness"]]
)

,case_id,faithfulness,context_precision,response_relevancy,factual_correctness
0,text_simple_01,0.481481,0.000,0.734717,0.80
1,text_complex_01,0.342105,0.325,0.663383,0.55
2,numeric_simple_01,0.233333,0.000,0.753206,0.15
3,numeric_complex_01,0.190476,0.000,0.774549,0.00
4,numeric_complex_02,0.200000,0.000,0.743218,0.15
5,comparison_01,0.000000,0.250,0.851608,0.15
6,robustness_noisy_01,0.631579,0.000,NaN,0.48
7,out_of_scope_01,0.000000,0.000,0.000000,0.53


Le principal problème se trouve au niveau du retriever, pas uniquement du LLM :

- Context Precision est nulle pour six questions sur huit.
- Les réponses sont souvent pertinentes dans leur formulation.
- Mais elles ne disposent pas des bonnes données, ce qui réduit Faithfulness et Factual Correctness.

C’est particulièrement visible pour les questions numériques :

- numeric_complex_01 obtient 0 en exactitude factuelle ;
- numeric_complex_02 obtient 0,15 ;
- comparison_01 obtient une pertinence élevée (0,85), mais une fidélité nulle et une exactitude de seulement 0,15.

Le LLM comprend donc la demande, mais FAISS ne lui fournit probablement pas toutes les lignes nécessaires pour filtrer, classer ou comparer.

In [3]:
for _, row in results_V01.iterrows():
    print("Question :")
    print(row["question"])

    print("\nRéponse :")
    print(row["answer"])

    print("\n" + "-" * 80 + "\n")

Question :
Quels sont les trois joueurs les plus souvent mentionnés dans les commentaires ?

Réponse :
Ah, excellente question ! D’après les échanges récents sur Reddit (et en croisant les tendances de *shit talk*, de débats stratégiques et de rivalités), voici les **trois joueurs les plus souvent cités** dans les commentaires animés, avec une nuance sur leur impact réel vs. leur image médiatique :

---

### **1. Tyrese Haliburton (Thunder OKC)**
**Pourquoi ?**
- **Le "shit talk" roi** : Haliburton est souvent accusé (à tort ou à raison) d’être le plus vocal des joueurs NBA, avec des répliques cinglantes contre ses adversaires (ex. : *"I’m not here to play for you"* vs. les Warriors en 2023). Les fans adorent (ou détestent) son côté provocateur, surtout en playoffs.
- **Rivalité historique** : Son duel avec Jayson Tatum (Celtics) ou Devin Booker (Warriors) a alimenté les débats sur la "mentalité de leader" vs. la "mentalité de joueur". Les commentaires sur Reddit (et les réseaux sociau

# V0.1 - Analyse des résultats de l’évaluation RAGAS 

## 1. Résultats globaux

| Métrique            | Moyenne approximative | Interprétation                                                                          |
| ------------------- | --------------------: | --------------------------------------------------------------------------------------- |
| Faithfulness        |                  0,26 | Faible : plusieurs affirmations ne sont pas soutenues par les contextes récupérés       |
| Context Precision   |                  0,07 | Très faible : les passages récupérés sont rarement adaptés à la question                |
| Response Relevancy  |                  0,65 | Correcte : les réponses restent généralement liées au sujet de la question              |
| Factual Correctness |                  0,35 | Faible : les réponses contiennent de nombreuses informations différentes des références |

Les réponses sont donc généralement liées au sujet demandé, mais elles utilisent rarement les bonnes informations et contiennent de nombreuses erreurs factuelles.

L’analyse manuelle montre également que certains scores RAGAS sont trop généreux. Les métriques automatiques doivent donc être complétées par une vérification humaine des réponses.

---

## 2. Analyse par question

### 2.1 Joueurs les plus souvent mentionnés

**Question :**

> Quels sont les trois joueurs les plus souvent mentionnés dans les commentaires ?

**Réponse attendue :**

> Reggie Miller, Stephen Curry et Dwyane Wade.

**Réponse générée :**

> Tyrese Haliburton, Jayson Tatum et Devin Booker.

La réponse est incorrecte : aucun des trois joueurs attendus n’est identifié.

Elle contient également plusieurs hallucinations :

* Tyrese Haliburton est associé au Thunder alors qu’il joue aux Pacers ;
* Devin Booker est associé aux Warriors alors qu’il joue aux Suns ;
* plusieurs rivalités, citations et statistiques sont inventées.

Le score `Factual Correctness` de `0,80` est donc incohérent avec le contenu réel de la réponse. Le modèle juge a probablement été influencé par la longueur de la réponse et par la présence de nombreux termes liés à la NBA.

**Verdict manuel : échec.**

---

### 2.2 Principaux sujets de débat

**Question :**

> Quels sont les principaux sujets de débat dans les commentaires des supporters ?

La réponse retrouve certains thèmes réellement présents :

* la médiatisation de la NBA ;
* les équipes issues de petits marchés ;
* la parité entre les équipes ;
* l’intérêt du public pour une finale entre le Thunder et les Pacers.

Cependant, plusieurs thèmes importants sont absents :

* les équipes et joueurs les plus impressionnants des playoffs ;
* l’efficacité et la place historique de Reggie Miller ;
* l’avantage du terrain ;
* le classement des équipes ;
* le système de play-in.

La réponse ajoute également des thèmes secondaires ou non suffisamment soutenus par les documents :

* la manipulation des résultats ;
* le trash-talk de Tyrese Haliburton ;
* l’arbitrage ;
* différentes citations et statistiques non présentes dans les sources.

**Verdict manuel : réponse partiellement correcte, mais incomplète et fortement enrichie par des informations inventées.**

---

### 2.3 Meilleur pourcentage à trois points

**Question :**

> Quels joueurs possèdent le meilleur pourcentage de réussite à trois points ?

**Réponse attendue :**

> Alondes Williams et Skal Labissiere avec 100 %, chacun sur une seule tentative.

La réponse générée désigne notamment Jayson Tatum, Jaren Jackson Jr., Tyrese Haliburton, Devin Booker et Jalen Brunson.

Elle ne retrouve donc aucun des deux joueurs attendus et invente plusieurs pourcentages, équipes et statistiques.

Le score `Factual Correctness` de `0,15` est cohérent avec cette réponse très éloignée de la référence.

**Verdict manuel : échec complet.**

---

### 2.4 Meilleur pourcentage avec au moins 100 tentatives

**Question :**

> Parmi les joueurs ayant tenté au moins 100 tirs à trois points, lequel possède le meilleur pourcentage de réussite ?

**Réponse attendue :**

> Seth Curry avec 45,6 % sur 184 tentatives.

**Réponse générée :**

> Reggie Miller avec 43,4 %.

La réponse utilise des données historiques externes au lieu d’appliquer le filtre demandé aux données du fichier Excel.

Le score `Factual Correctness` de `0` correspond correctement à cet échec.

**Verdict manuel : échec complet.**

---

### 2.5 Cinq meilleurs marqueurs

**Question :**

> Quels sont les cinq joueurs ayant marqué le plus de points, classés du premier au cinquième ?

**Classement attendu :**

1. Shai Gilgeous-Alexander : 2 485 points ;
2. Anthony Edwards : 2 180 points ;
3. Nikola Jokić : 2 072 points ;
4. Giannis Antetokounmpo : 2 037 points ;
5. Jayson Tatum : 1 930 points.

La réponse générée propose principalement :

1. Jayson Tatum ;
2. Nikola Jokić ;
3. Giannis Antetokounmpo ;
4. Luka Dončić ;
5. Jrue Holiday.

Elle mentionne ensuite Shai Gilgeous-Alexander dans son développement, mais ne produit jamais le classement attendu. Elle confond également les points totaux et les moyennes de points par match.

La présence de quelques joueurs appartenant réellement au classement explique probablement le score `Factual Correctness` de `0,15`, mais la réponse finale reste incorrecte.

**Verdict manuel : échec.**

---

### 2.6 Comparaison des rebonds

**Question :**

> Compare le nombre total de rebonds de Shai Gilgeous-Alexander et d’Anthony Edwards.

**Réponse attendue :**

> Shai Gilgeous-Alexander totalise 380 rebonds, contre 450 pour Anthony Edwards. Anthony Edwards a donc capté 70 rebonds de plus.

La réponse générée estime environ 1 800 rebonds pour Shai Gilgeous-Alexander et 1 200 pour Anthony Edwards. Elle conclut donc, à tort, que Shai est le meilleur rebondeur.

Elle contient aussi plusieurs hallucinations :

* Shai Gilgeous-Alexander est présenté comme un pivot ;
* Anthony Edwards est également assimilé à un intérieur ;
* les totaux et pourcentages de rebonds sont inventés ;
* les moyennes par match sont très éloignées des données réelles.

Le score élevé de `Response Relevancy` (`0,85`) signifie seulement que la réponse parle bien des deux joueurs et des rebonds. Il ne mesure pas l’exactitude des nombres ou de la conclusion.

**Verdict manuel : échec complet.**

---

### 2.7 Robustesse face aux fautes

**Question :**

> c ki les joueur ki on le meilleur pourcentaj a 3 points ?

Le système comprend correctement l’intention malgré les fautes. La robustesse linguistique est donc satisfaisante.

Cependant, la réponse reprend un classement incorrect proche de celui fourni pour la question numérique simple. Elle ne cite pas Alondes Williams et Skal Labissiere.

La valeur manquante de `Response Relevancy` correspond à un échec technique du calcul de la métrique. Elle ne doit pas être interprétée comme un score nul.

**Verdict manuel :**

* compréhension de la question : réussie ;
* exactitude de la réponse : échouée.

---

### 2.8 Question hors périmètre

**Question :**

> Quel temps fera-t-il demain à Toulouse ?

Le système indique correctement que les données fournies ne contiennent pas d’informations météorologiques. Le mécanisme de refus fonctionne donc.

Cependant, la réponse continue ensuite sur plusieurs paragraphes avec des analogies entre la météo et la NBA ainsi que de nouvelles affirmations non vérifiées.

Elle aurait dû s’arrêter après une phrase, par exemple :

> Je ne dispose pas de données météorologiques permettant de répondre à cette question.

Cela explique les résultats suivants :

* `Response Relevancy = 0` : la majorité de la réponse est inutile par rapport à la question ;
* `Faithfulness = 0` : les développements supplémentaires ne sont pas soutenus par les données ;
* `Factual Correctness = 0,53` : l’idée principale correspond partiellement à la réponse de référence.

**Verdict manuel : refus fonctionnellement correct, mais réponse trop longue et contenant des hallucinations.**

---

## 3. Bilan manuel

Sur les huit réponses évaluées :

* aucune réponse métier n’est entièrement correcte ;
* une réponse est partiellement correcte : les principaux sujets de débat ;
* une réponse refuse correctement une demande hors périmètre, mais de manière trop longue ;
* six réponses sont incorrectes ;
* le système comprend correctement la question comportant des fautes, mais fournit une réponse factuellement incorrecte.

Les résultats montrent donc que la pertinence thématique est meilleure que l’exactitude factuelle. Le système comprend généralement le sujet de la demande, mais ne parvient pas à récupérer ou exploiter correctement les données nécessaires.

---

## 4. Limites identifiées

### 4.1 Récupération insuffisante

La valeur moyenne très faible de `Context Precision` indique que les chunks transmis au LLM sont rarement les plus utiles pour répondre aux questions.

Le modèle doit alors produire une réponse avec des informations incomplètes ou non pertinentes.

### 4.2 Limites de FAISS pour les calculs globaux

Les questions demandant de :

* calculer un maximum ;
* appliquer un filtre ;
* classer plusieurs joueurs ;
* comparer des valeurs ;
* compter les mentions dans l’ensemble des documents ;

nécessitent une analyse globale des données.

Une recherche sémantique limitée aux cinq chunks les plus proches ne garantit pas que toutes les lignes nécessaires seront récupérées. FAISS recherche des passages sémantiquement proches, mais ne réalise pas directement de filtre, de tri ou d’agrégation sur l’ensemble du tableau.

### 4.3 Prompt de génération trop permissif

Le modèle adopte systématiquement un style de « débat analytique » et produit des réponses longues, même lorsque la question demande un résultat numérique simple.

Ce comportement favorise :

* l’ajout d’informations inutiles ;
* l’utilisation de connaissances générales externes ;
* l’invention de statistiques ;
* les erreurs d’équipes, de saisons et de positions ;
* l’éloignement par rapport au contexte récupéré.

Le prompt devrait imposer au modèle :

1. d’utiliser uniquement les informations présentes dans le contexte ;
2. de ne jamais compléter une information manquante avec ses connaissances générales ;
3. de signaler clairement lorsque les données sont insuffisantes ;
4. de répondre directement et brièvement ;
5. de ne pas transformer systématiquement la réponse en débat.

### 4.4 Limites du modèle juge

Certains scores de `Factual Correctness` ne correspondent pas à la qualité réelle des réponses.

L’exemple le plus évident est la première question :

* réponse entièrement incorrecte ;
* `Factual Correctness = 0,80`.

Le modèle juge `ministral-3b-2512` semble donc avoir des difficultés à comparer précisément une réponse longue avec une référence courte. Les scores automatiques doivent rester accompagnés d’une vérification manuelle.

---

## 5. Pistes d’amélioration

Les principales améliorations possibles sont :

1. utiliser un traitement structuré pour les questions numériques ;
2. appliquer directement les filtres, tris et agrégations sur le DataFrame ;
3. réserver FAISS aux questions textuelles et à la recherche dans les commentaires Reddit ;
4. router les questions vers le bon type de traitement avant la génération ;
5. renforcer le prompt afin d’interdire les connaissances externes et les valeurs inventées ;
6. produire des réponses plus courtes et directement centrées sur la question ;
7. utiliser un modèle juge plus performant pour les métriques RAGAS ;
8. conserver une vérification humaine sur un échantillon de réponses.

Une architecture hybride serait plus adaptée :

* questions textuelles sur Reddit : recherche vectorielle avec FAISS ;
* questions numériques sur les joueurs : requêtes structurées sur le DataFrame ;
* génération finale : formulation concise à partir des résultats calculés.

---

## 6. Conclusion

> L’analyse manuelle révèle que les réponses restent généralement liées au sujet, mais qu’elles contiennent de nombreuses erreurs factuelles et hallucinations. Les scores automatiques, notamment l’exactitude factuelle, doivent donc être interprétés avec prudence. Les principales limites proviennent de l’utilisation d’une recherche vectorielle pour des calculs globaux et d’un prompt de génération trop permissif. Une architecture hybride combinant recherche sémantique et traitement structuré des statistiques permettrait d’améliorer fortement la fiabilité des réponses.


In [4]:


display(
    results_V01[["case_id", "faithfulness", "context_precision", "response_relevancy", "factual_correctness"]]
)

results_V02 = pd.read_csv(
    "results/v0.2_pydantic_ai_results.csv"
)

display(
    results_V02[["case_id", "faithfulness", "context_precision", "response_relevancy", "factual_correctness"]]
)

,case_id,faithfulness,context_precision,response_relevancy,factual_correctness
0,text_simple_01,0.481481,0.000,0.734717,0.80
1,text_complex_01,0.342105,0.325,0.663383,0.55
2,numeric_simple_01,0.233333,0.000,0.753206,0.15
3,numeric_complex_01,0.190476,0.000,0.774549,0.00
4,numeric_complex_02,0.200000,0.000,0.743218,0.15
5,comparison_01,0.000000,0.250,0.851608,0.15
6,robustness_noisy_01,0.631579,0.000,NaN,0.48
7,out_of_scope_01,0.000000,0.000,0.000000,0.53


,case_id,faithfulness,context_precision,response_relevancy,factual_correctness
0,text_simple_01,0.720000,1.00,0.746829,0.19
1,text_complex_01,NaN,NaN,0.820751,0.84
2,numeric_simple_01,0.657143,0.00,0.777291,0.06
3,numeric_complex_01,0.086957,0.25,0.834734,0.47
4,numeric_complex_02,0.093750,0.00,0.742770,0.29
5,comparison_01,0.000000,0.25,0.855278,0.68
6,robustness_noisy_01,0.500000,0.00,0.708446,0.23
7,out_of_scope_01,0.105263,0.00,0.000000,0.57


# V0.2 - Analyse Ragas 

La version **v0.2** obtient des résultats globalement supérieurs à la baseline, avec une amélioration des quatre métriques moyennes : **faithfulness (0,309)**, **context precision (0,214)**, **response relevancy (0,686)** et **factual correctness (0,416)**.

L’intégration de **Pydantic et Pydantic AI** sécurise les flux et conserve le bon fonctionnement du pipeline RAG. Ces résultats restent toutefois à interpréter avec prudence en raison de certaines valeurs manquantes et de la variabilité liée à l’évaluation par LLM.


In [5]:
display(
    results_V01[["case_id", "faithfulness", "context_precision", "response_relevancy", "factual_correctness"]]
)

results_V03 = pd.read_csv(
    "results/v0.3_sql_results.csv"
)

display(
    results_V03[["case_id", "faithfulness", "context_precision", "response_relevancy", "factual_correctness"]]
)

,case_id,faithfulness,context_precision,response_relevancy,factual_correctness
0,text_simple_01,0.481481,0.000,0.734717,0.80
1,text_complex_01,0.342105,0.325,0.663383,0.55
2,numeric_simple_01,0.233333,0.000,0.753206,0.15
3,numeric_complex_01,0.190476,0.000,0.774549,0.00
4,numeric_complex_02,0.200000,0.000,0.743218,0.15
5,comparison_01,0.000000,0.250,0.851608,0.15
6,robustness_noisy_01,0.631579,0.000,NaN,0.48
7,out_of_scope_01,0.000000,0.000,0.000000,0.53


,case_id,faithfulness,context_precision,response_relevancy,factual_correctness
0,text_simple_01,NaN,0.000000,0.000000,0.00
1,text_complex_01,1.000000,0.250000,0.801893,0.21
2,numeric_simple_01,1.000000,0.587302,0.805857,0.22
3,numeric_complex_01,0.666667,0.166667,0.840104,0.00
4,numeric_complex_02,1.000000,0.166667,0.815115,1.00
5,comparison_01,NaN,0.166667,0.861286,1.00
6,robustness_noisy_01,0.857143,0.166667,0.714024,0.00
7,out_of_scope_01,0.600000,0.000000,0.000000,0.33


In [6]:
for _, row in results_V03.iterrows():
    print("Question :")
    print(row["question"])

    print("\nRéponse attendue :")
    print(row["reference"])

    print("\nRéponse Obtenue:")
    print(row["answer"])

    print("\n" + "-" * 80 + "\n")

Question :
Quels sont les trois joueurs les plus souvent mentionnés dans les commentaires ?

Réponse attendue :
Les trois joueurs les plus souvent mentionnés dans les commentaires sont Reggie Miller, Stephen Curry et Dwyane Wade, dans cet ordre.

Réponse Obtenue:
Les commentaires documentés ne permettent pas d'identifier clairement les trois joueurs les plus souvent mentionnés dans les échanges sur Reddit. Les références disponibles concernent principalement des discussions générales ou des thèmes liés à la NBA, sans attribution directe et répétée à des joueurs spécifiques.

--------------------------------------------------------------------------------

Question :
Quels sont les principaux sujets de débat dans les commentaires des supporters ?

Réponse attendue :
Les principaux débats portent sur les équipes et joueurs les plus impressionnants des playoffs, l'intérêt médiatique et les audiences d'une finale entre équipes de petits marchés, l'efficacité et la place historique de Reggi

## Analyse de la V03 : agent avec tool SQL

Cette analyse combine les scores RAGAS, une évaluation humaine
des réponses et l'examen des contextes et des traces Logfire.

Les métriques non calculées sont conservées comme valeurs
manquantes et exclues des moyennes.

In [19]:
display()

metrics = [
    "faithfulness",
    "context_precision",
    "response_relevancy",
    "factual_correctness",
]

print("Nombre de cas V01 :", len(results_V01))
print("Nombre de cas V03 :", len(results_V03))

print(
    "Mêmes identifiants :",
    set(results_V01["case_id"]) == set(results_V03["case_id"]),
)

display(results_V03.info())

display(
    results_V03[
        ["case_id", "category", "question"] + metrics
    ]
)

summary_V03 = pd.DataFrame({
    "Moyenne": results_V03[metrics].mean(),
    "Scores calculés": results_V03[metrics].count(),
    "Scores manquants": results_V03[metrics].isna().sum(),
})

display(summary_V03.round(3))

Nombre de cas V01 : 8
Nombre de cas V03 : 8
Mêmes identifiants : True
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   case_id              8 non-null      object 
 1   category             8 non-null      object 
 2   question             8 non-null      object 
 3   reference            8 non-null      object 
 4   answer               8 non-null      object 
 5   retrieved_contexts   8 non-null      object 
 6   faithfulness         6 non-null      float64
 7   context_precision    8 non-null      float64
 8   response_relevancy   8 non-null      float64
 9   factual_correctness  8 non-null      float64
dtypes: float64(4), object(6)
memory usage: 772.0+ bytes


None

,case_id,category,question,faithfulness,context_precision,response_relevancy,factual_correctness
0,text_simple_01,text_simple,Quels sont les trois joueurs les plus souvent ...,NaN,0.000000,0.000000,0.00
1,text_complex_01,text_complex,Quels sont les principaux sujets de débat dans...,1.000000,0.250000,0.801893,0.21
2,numeric_simple_01,numeric_simple,Quels joueurs possèdent le meilleur pourcentag...,1.000000,0.587302,0.805857,0.22
3,numeric_complex_01,numeric_complex,Parmi les joueurs ayant tenté au moins 100 tir...,0.666667,0.166667,0.840104,0.00
4,numeric_complex_02,numeric_complex,Quels sont les cinq joueurs ayant marqué le pl...,1.000000,0.166667,0.815115,1.00
5,comparison_01,comparison,Compare le nombre total de rebonds de Shai Gil...,NaN,0.166667,0.861286,1.00
6,robustness_noisy_01,robustness_noisy,c ki les joueur ki on le meilleur pourcentaj a...,0.857143,0.166667,0.714024,0.00
7,out_of_scope_01,out_of_scope,Quel temps fera-t-il demain à Toulouse ?,0.600000,0.000000,0.000000,0.33


,Moyenne,Scores calculés,Scores manquants
faithfulness,0.854,6,2
context_precision,0.188,8,0
response_relevancy,0.605,8,0
factual_correctness,0.345,8,0


### Analyse question 1

In [8]:
import ast

row = results_V03.loc[
    results_V03["case_id"] == "text_simple_01"
].iloc[0]

print("QUESTION :")
print(row["question"])

print("\nRÉPONSE ATTENDUE :")
print(row["reference"])

print("\nRÉPONSE OBTENUE :")
print(row["answer"])

# Le CSV stocke la liste des contextes sous forme de texte.
contexts = ast.literal_eval(row["retrieved_contexts"])

for i, context in enumerate(contexts, start=1):
    print(f"\n{'-' * 30} CONTEXTE {i} {'-' * 30}\n")
    print(context)

QUESTION :
Quels sont les trois joueurs les plus souvent mentionnés dans les commentaires ?

RÉPONSE ATTENDUE :
Les trois joueurs les plus souvent mentionnés dans les commentaires sont Reggie Miller, Stephen Curry et Dwyane Wade, dans cet ordre.

RÉPONSE OBTENUE :
Les commentaires documentés ne permettent pas d'identifier clairement les trois joueurs les plus souvent mentionnés dans les échanges sur Reddit. Les références disponibles concernent principalement des discussions générales ou des thèmes liés à la NBA, sans attribution directe et répétée à des joueurs spécifiques.

------------------------------ CONTEXTE 1 ------------------------------

41                     USG%                Usage Rate – % des actions utilisées par le joueur
42                     PACE                        Rythme de jeu (possessions par 48 minutes)
43                      PIE           Player Impact Estimate – évaluation globale de l’impact
44                     POSS                                No

### Cas text_simple_01 — Joueurs les plus mentionnés

![Trace Logfire de la question 1](logfire/Logfire_question_1.png)

**Résultat :** le classement attendu n'est pas fourni.

**Contextes récupérés :** quatre passages issus de l'Excel sont
hors sujet. Le cinquième contient des commentaires Reddit, mais
ne fournit aucun comptage permettant de classer les joueurs
par fréquence de mention.

**Réponse :** l'abstention évite un classement non justifié.
Cependant, la formulation généralise les limites des extraits
récupérés à l'ensemble des commentaires et minimise la présence
de mentions de joueurs.

**Diagnostic :** la recherche documentaire ne fournit pas les
preuves nécessaires. De plus, un classement global par fréquence
nécessite un comptage sur le corpus ; les cinq passages les plus
similaires ne garantissent pas ce classement.

**Observation Logfire et Tool SQL :** la trace contient une recherche FAISS
et un seul appel au modèle, sans appel au tool SQL.
Le pipeline dure environ 29 secondes, dont 28,6 secondes
pour l'appel au modèle.
L'absence d'appel SQL est cohérente avec cette question
La base de statistiques NBA ne permet pas de compter les mentions
dans les commentaires. 

**Métriques :** les scores nuls de pertinence et d'exactitude
reflètent l'absence de la réponse attendue. Le score de fidélité
est manquant à cause d'une erreur de calcul du juge.

**Pistes à tester ultérieurement :**
- Filtrer la recherche vers les documents Reddit pour les questions
  sur les commentaires.
- Nettoyer les publicités et les éléments d'interface des documents.
- Prévoir un comptage des mentions pour les questions de fréquence.
- Limiter les formulations d'abstention aux extraits disponibles.


### Analyse question 2

In [9]:
row = results_V03.loc[
    results_V03["case_id"] == "text_complex_01"
].iloc[0]

print("QUESTION :")
print(row["question"])

print("\nRÉPONSE ATTENDUE :")
print(row["reference"])

print("\nRÉPONSE OBTENUE :")
print(row["answer"])

contexts = ast.literal_eval(row["retrieved_contexts"])

for i, context in enumerate(contexts, start=1):
    print(f"\n{'-' * 30} CONTEXTE {i} {'-' * 30}\n")
    print(context)

QUESTION :
Quels sont les principaux sujets de débat dans les commentaires des supporters ?

RÉPONSE ATTENDUE :
Les principaux débats portent sur les équipes et joueurs les plus impressionnants des playoffs, l'intérêt médiatique et les audiences d'une finale entre équipes de petits marchés, l'efficacité et la place historique de Reggie Miller, ainsi que l'avantage du terrain, le classement des équipes et le système de play-in.

RÉPONSE OBTENUE :
Les principaux sujets de débat dans les commentaires des supporters concernent principalement :

1. **L'équité entre les équipes et la parité dans la NBA**, notamment en raison des contraintes budgétaires (hard cap) et leur impact sur les performances des petits marchés.
2. **La rivalité et la toxicité entre les supporters de deux équipes statistiques parmi les meilleures en playoffs**, ainsi que les attentes autour de leur confrontation en Finale NBA.
3. **L'importance des joueurs individuels par rapport aux équipes**, avec une tendance à priv

### Cas text_complex_01 — Principaux sujets de débat

![Trace Logfire de la question 2](logfire/Logfire_question_2.png)

**Résultat :** la réponse identifie plusieurs débats pertinents,
mais ne couvre qu’une partie des thèmes attendus.

**Contextes récupérés :** quatre passages proviennent du même fil
Reddit et un passage Excel est hors sujet. Les extraits couvrent
la parité, les petits marchés, la rivalité entre supporters et
l’attachement aux stars. Ils ne couvrent pas Reggie Miller,
l’avantage du terrain, le classement ou le play-in.

**Réponse :** elle reprend correctement plusieurs thèmes présents.
Cependant, les audiences restent peu explicitées et certains
passages concernant la NFL sont généralisés à la NBA.

**Diagnostic :** la recherche manque de diversité pour produire
une synthèse de l’ensemble des commentaires. Les omissions
proviennent principalement des contextes récupérés, avec quelques
imprécisions supplémentaires dans la synthèse.

**Observation Logfire et tool SQL :** la trace montre une recherche
FAISS de 383 ms, suivie d’un seul appel au modèle d’environ
1,55 seconde. Le pipeline dure environ 1,95 seconde.
Aucun appel au tool SQL n’est observé, ce qui est adapté :
la question porte sur les commentaires, pas sur les statistiques.

**Métriques :** la fidélité de 1,00 et la pertinence de 0,80
concordent avec une réponse largement fondée sur les extraits.
La précision des contextes de 0,25 et l’exactitude factuelle
de 0,21 signalent une couverture limitée. Ce dernier score
ne signifie pas que tous les thèmes présentés sont faux.

**Pistes à tester ultérieurement :**
- Filtrer la recherche vers les documents Reddit.
- Diversifier les extraits pour les questions de synthèse.
- Nettoyer les publicités et les éléments d’interface.
- Distinguer les commentaires NBA des comparaisons avec la NFL.


### Analyse Question 3

In [10]:
row = results_V03.loc[
    results_V03["case_id"] == "numeric_simple_01"
].iloc[0]

print("QUESTION :")
print(row["question"])

print("\nRÉPONSE ATTENDUE :")
print(row["reference"])

print("\nRÉPONSE OBTENUE :")
print(row["answer"])

contexts = ast.literal_eval(row["retrieved_contexts"])

for i, context in enumerate(contexts, start=1):
    print(f"\n{'-' * 30} CONTEXTE {i} {'-' * 30}\n")
    print(context)

QUESTION :
Quels joueurs possèdent le meilleur pourcentage de réussite à trois points ?

RÉPONSE ATTENDUE :
Alondes Williams et Skal Labissiere possèdent le meilleur pourcentage de réussite à trois points avec 100 %, chacun ayant réussi son unique tentative.

RÉPONSE OBTENUE :
Voici les cinq joueurs avec le meilleur pourcentage de réussite à trois points pour la saison 2024-25 :

| Rang | Joueur               | Valeur 3P% |
|------|----------------------|------------|
| 1    | Alondes Williams      | 100,0%     |
| 2    | Skal Labissière      | 100,0%     |
| 3    | PJ Dozier             | 66,7%      |
| 4    | Patrick Baldwin Jr.  | 56,5%      |
| 5    | Dru Smith             | 53,3%      |

Les joueurs **Alondes Williams** et **Skal Labissière** détiennent le meilleur pourcentage à 100 %.

------------------------------ CONTEXTE 1 ------------------------------

Dictionnaire des données                                                        Unnamed: 1
0                    Player     

### Cas numeric_simple_01 — Meilleur pourcentage à trois points

![Trace Logfire de la question 3](logfire/Logfire_question_3.png)

**Résultat :** les deux joueurs attendus sont correctement identifiés :
Alondes Williams et Skal Labissiere, avec 100 %. La réponse ne précise
pas que chacun n’a tenté qu’un seul tir.

**Contextes récupérés :** les cinq passages FAISS ne permettent pas
d’établir le classement. Les deux résultats SQL fournissent les mêmes
cinq joueurs et pourcentages, repris correctement dans la réponse.

**Réponse :** les noms et les valeurs correspondent aux résultats SQL.
Le tableau propose cinq joueurs, puis souligne les deux premiers
ex æquo. Le faible nombre de tentatives manque pour contextualiser
leur pourcentage de 100 %.

**Diagnostic :** le tool SQL permet de répondre correctement malgré
des contextes documentaires insuffisants. Les requêtes utilisent
la bonne colonne, three_point_pct, avec un tri décroissant.
Cependant, elles ne récupèrent pas three_points_attempted et
le second appel répète le classement sans apporter d’information utile.

**Observation Logfire et tool SQL :** la trace confirme deux appels
au tool SQL et trois appels au modèle. La recherche FAISS dure
263 ms et le pipeline environ 5,18 secondes. Les deux exécutions
SQL durent environ 1,75 seconde et 692 ms.

**Métriques :** la fidélité de 1,00 confirme que la réponse est
soutenue par les résultats SQL. La pertinence est de 0,81 et
la précision des contextes de 0,59. L’exactitude factuelle de 0,22
paraît sévère au regard des noms et pourcentages corrects :
l’omission des tentatives est réelle, mais ne suffit pas à expliquer
ce score sans examiner les jugements détaillés de RAGAS.

**Pistes d’amélioration à tester :**
- Récupérer et afficher le nombre de tentatives avec les pourcentages.
- Éviter les appels SQL répétés lorsqu’un résultat suffit.
- Réduire les contextes FAISS inutiles pour les classements statistiques.
- Examiner les jugements de RAGAS pour comprendre le faible score
  d’exactitude factuelle.

### Analyse Question 4

In [11]:
row = results_V03.loc[
    results_V03["case_id"] == "numeric_complex_01"
].iloc[0]

print("QUESTION :")
print(row["question"])

print("\nRÉPONSE ATTENDUE :")
print(row["reference"])

print("\nRÉPONSE OBTENUE :")
print(row["answer"])

contexts = ast.literal_eval(row["retrieved_contexts"])

for i, context in enumerate(contexts, start=1):
    print(f"\n{'-' * 30} CONTEXTE {i} {'-' * 30}\n")
    print(context)

QUESTION :
Parmi les joueurs ayant tenté au moins 100 tirs à trois points, lequel possède le meilleur pourcentage de réussite ?

RÉPONSE ATTENDUE :
Seth Curry possède le meilleur pourcentage de réussite parmi les joueurs ayant tenté au moins 100 tirs à trois points, avec 45,6 % sur 184 tentatives.

RÉPONSE OBTENUE :
Seth Curry détient le meilleur pourcentage de réussite aux tirs à trois points parmi les joueurs ayant tenté au moins 100 tirs à trois points en saison 2024-25, avec un **45,6 %**.

*(Aucune URL n'est disponible pour ce joueur.)*

------------------------------ CONTEXTE 1 ------------------------------

27                      TD3            Triple-doubles (≥10 dans trois catégories principales)
28                    + / -  Plus-Minus (écart de score lorsque le joueur est sur le terrain)
29                   OFFRTG             Offensive Rating (points marqués par 100 possessions)
30                   DEFRTG           Defensive Rating (points encaissés par 100 possessions)
3

### Cas numeric_complex_01 — Pourcentage à trois points avec au moins 100 tentatives

![Trace Logfire de la question 4](logfire/Logfire_question_4.png)

**Résultat :** Seth Curry et son pourcentage de 45,6 % sont
correctement identifiés. Les 184 tentatives mentionnées dans
la référence ne sont pas précisées.

**Contextes récupérés :** les cinq passages FAISS ne permettent
pas de répondre à la question. Le résultat SQL fournit directement
le joueur et son pourcentage, après application du filtre demandé.

**Réponse :** elle restitue correctement le résultat SQL.
Cependant, la remarque sur l’absence d’URL est inutile et
non justifiée : la requête ne sélectionne pas player_url.
Une colonne non récupérée ne signifie pas que la donnée est absente.

**Diagnostic :** la requête utilise correctement
three_points_attempted >= 100, trie three_point_pct par ordre
décroissant et limite le résultat à un joueur. Le calcul répond
donc à la demande, mais les colonnes sélectionnées ne permettent
pas de préciser le nombre de tentatives.

**Observation Logfire et tool SQL :** la trace confirme un seul
appel au tool SQL et deux appels au modèle. La recherche FAISS
dure 243 ms, l’exécution du tool environ 2,81 secondes et
le pipeline environ 9,20 secondes.

**Métriques :** la pertinence de 0,84 concorde avec une réponse
qui répond à la question. La fidélité de 0,67 peut être affectée
par la remarque non étayée sur l’URL, sans que cette cause soit
confirmée. La précision des contextes est de 0,17.
L’exactitude factuelle de 0,00 ne reflète pas les deux éléments
corrects observés : le joueur et son pourcentage. Les jugements
détaillés du juge seraient nécessaires pour expliquer ce score.

**Pistes d’amélioration à tester :**
- Sélectionner le nombre de tentatives pour contextualiser le résultat.
- Ne mentionner les liens que lorsqu’ils sont demandés.
- Ne pas déclarer une donnée absente lorsqu’elle n’a pas été récupérée.
- Réduire les contextes FAISS inutiles pour les questions statistiques.
- Examiner les jugements RAGAS lorsque les scores divergent
  de la vérification humaine.

### Analyse questio 5

In [12]:
row = results_V03.loc[
    results_V03["case_id"] == "numeric_complex_02"
].iloc[0]

print("QUESTION :")
print(row["question"])

print("\nRÉPONSE ATTENDUE :")
print(row["reference"])

print("\nRÉPONSE OBTENUE :")
print(row["answer"])

contexts = ast.literal_eval(row["retrieved_contexts"])

for i, context in enumerate(contexts, start=1):
    print(f"\n{'-' * 30} CONTEXTE {i} {'-' * 30}\n")
    print(context)

QUESTION :
Quels sont les cinq joueurs ayant marqué le plus de points, classés du premier au cinquième ?

RÉPONSE ATTENDUE :
Les cinq joueurs ayant marqué le plus de points sont Shai Gilgeous-Alexander avec 2 485 points, Anthony Edwards avec 2 180 points, Nikola Jokić avec 2 072 points, Giannis Antetokounmpo avec 2 037 points et Jayson Tatum avec 1 930 points, dans cet ordre.

RÉPONSE OBTENUE :
Voici les cinq joueurs ayant marqué le plus de points lors de la saison 2024-25 :

| Rang | Joueur                     | Nombre de points totaux |
|------|----------------------------|--------------------------|
| 1    | Shai Gilgeous-Alexander     | 2 485                    |
| 2    | Anthony Edwards            | 2 180                    |
| 3    | Nikola Jokić                | 2 072                    |
| 4    | Giannis Antetokounmpo      | 2 037                    |
| 5    | Jayson Tatum               | 1 930                    |

------------------------------ CONTEXTE 1 --------------------

### Cas numeric_complex_02 — Classement des cinq meilleurs marqueurs

![Trace Logfire de la question 5](logfire/Logfire_question_5.png)

**Résultat :** les cinq joueurs, leurs totaux de points et leur
ordre correspondent exactement à la réponse attendue.

**Contextes récupérés :** les passages FAISS ne fournissent pas
le classement complet. Seul le contexte 2 donne un total utile :
2 485 points pour Shai Gilgeous-Alexander. Le résultat SQL contient
les cinq joueurs et toutes les valeurs nécessaires.

**Réponse :** le tableau restitue correctement les résultats SQL,
avec des rangs explicites et une unité claire. Aucun ajout inutile
ni affirmation non étayée n’est observé.

**Diagnostic :** la requête sélectionne correctement points_total,
filtre la saison 2024-25 et applique un tri décroissant avec LIMIT 5.
Le tool SQL fournit une réponse complète malgré des passages FAISS
peu utiles. Le dictionnaire décrit les points comme une moyenne,
alors que le tableau et les valeurs SQL correspondent ici à des
totaux : cette incohérence documentaire reste à clarifier.

**Observation Logfire et tool SQL :** la trace confirme un seul
appel au tool SQL et deux appels au modèle. La recherche FAISS
dure 689 ms et le tool SQL environ 1,03 seconde. Le pipeline dure
19,6 secondes, dont 17,3 secondes pour le dernier appel au modèle.
L’essentiel du temps est donc consacré à cet appel, sans que
la trace permette d’en déterminer la cause.

**Métriques :** la fidélité et l’exactitude factuelle de 1,00
concordent avec la vérification humaine. La pertinence est de 0,82.
La précision des contextes de 0,17 est cohérente avec une preuve
SQL placée en dernier parmi six contextes, dont plusieurs sont
peu utiles pour répondre.

**Pistes d’amélioration à tester :**
- Réduire les passages FAISS inutiles pour les classements statistiques.
- Clarifier les définitions contradictoires entre le dictionnaire
  Excel et les données importées.
- Comparer les durées sur plusieurs exécutions pour vérifier
  si la lenteur du dernier appel au modèle se répète.
- Conserver ce cas pour vérifier que les prochaines modifications
  préservent un classement complet et correct.

### Analyse Question 6

In [13]:
row = results_V03.loc[
    results_V03["case_id"] == "comparison_01"
].iloc[0]

print("QUESTION :")
print(row["question"])

print("\nRÉPONSE ATTENDUE :")
print(row["reference"])

print("\nRÉPONSE OBTENUE :")
print(row["answer"])

contexts = ast.literal_eval(row["retrieved_contexts"])

for i, context in enumerate(contexts, start=1):
    print(f"\n{'-' * 30} CONTEXTE {i} {'-' * 30}\n")
    print(context)

QUESTION :
Compare le nombre total de rebonds de Shai Gilgeous-Alexander et d’Anthony Edwards.

RÉPONSE ATTENDUE :
Shai Gilgeous-Alexander totalise 380 rebonds, contre 450 pour Anthony Edwards. Anthony Edwards a donc capté 70 rebonds de plus.

RÉPONSE OBTENUE :
En saison 2024-25, **Shai Gilgeous-Alexander** a marqué **380 rebonds totaux**, tandis qu'**Anthony Edwards** en a totalisé **450 rebonds** pour la même saison.

------------------------------ CONTEXTE 1 ------------------------------

84   Analyse du top 15 des joueurs en nombre de points                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN
85                                                 NaN                      NaN                          NaN                               NaN                                          NaN                              

### Cas comparison_01 — Comparaison des rebonds de deux joueurs

![Trace Logfire de la question 6](logfire/Logfire_question_6.png)

**Résultat :** les deux totaux sont corrects : 380 rebonds pour
Shai Gilgeous-Alexander et 450 pour Anthony Edwards.
La différence de 70 rebonds n’est pas explicitée.

**Contextes récupérés :** les cinq passages FAISS ne fournissent
pas les deux totaux nécessaires. Le contexte 1 mentionne seulement
les rebonds offensifs de Shai Gilgeous-Alexander. Le résultat SQL
fournit les rebonds totaux des deux joueurs.

**Réponse :** elle restitue correctement les valeurs, mais juxtapose
les totaux sans préciser qu’Anthony Edwards a capté 70 rebonds
de plus. La formulation « a marqué des rebonds » est maladroite :
« a capté » ou « a totalisé » serait plus adapté.

**Diagnostic :** la requête utilise correctement total_rebounds,
sélectionne les deux joueurs et filtre la saison 2024-25.
La récupération fonctionne ; l’amélioration concerne surtout
la formulation et l’explicitation de la comparaison.

**Observation Logfire et tool SQL :** la trace confirme un seul
appel au tool SQL et deux appels au modèle. La recherche FAISS
dure 379 ms, le tool SQL environ 774 ms et le pipeline
environ 2,23 secondes.

**Métriques :** l’exactitude factuelle de 1,00 confirme les valeurs
correctes, mais ne traduit pas l’omission de l’écart attendu.
La pertinence est de 0,86 et la précision des contextes de 0,17.
La fidélité est manquante à cause d’une erreur de calcul du juge ;
cela ne permet pas de conclure à un défaut de fidélité.

**Pistes d’amélioration à tester :**
- Pour une comparaison, préciser qui possède la valeur la plus
  élevée et calculer l’écart.
- Employer un vocabulaire adapté aux statistiques concernées.
- Réduire les passages FAISS inutiles pour les questions statistiques.
- Compléter les métriques par une vérification humaine
  de la complétude de la réponse.

### Analyse question 7

In [14]:
row = results_V03.loc[
    results_V03["question"].str.contains(
        "pourcentaj", case=False, na=False
    )
].iloc[0]

print("\nQUESTION :")
print(row["question"])

print("\nRÉPONSE ATTENDUE :")
print(row["reference"])

print("\nRÉPONSE OBTENUE :")
print(row["answer"])

contexts = ast.literal_eval(row["retrieved_contexts"])

for i, context in enumerate(contexts, start=1):
    print(f"\n{'-' * 30} CONTEXTE {i} {'-' * 30}\n")
    print(context)


QUESTION :
c ki les joueur ki on le meilleur pourcentaj a 3 points ?

RÉPONSE ATTENDUE :
Alondes Williams et Skal Labissiere possèdent le meilleur pourcentage de réussite à trois points avec 100 %, chacun sur une seule tentative.

RÉPONSE OBTENUE :
Voici les cinq joueurs avec le pourcentage de réussite aux tirs à 3 points le plus élevé pour la saison 2024-25 :

| Rang | Joueur                     | 3P%   |
|------|-----------------------------|-------|
| 1    | Alondes Williams             | 100%  |
| 2    | Skal Labissiere             | 100%  |
| 3    | PJ Dozier                   | 66,7% |
| 4    | Patrick Baldwin Jr.        | 56,5% |
| 5    | Dru Smith                   | 53,3% |

Pour plus de détails sur leur performance ou leur équipe, je peux fournir des liens vers leurs fiches NBA si nécessaire.

------------------------------ CONTEXTE 1 ------------------------------

41                     USG%                Usage Rate – % des actions utilisées par le joueur
42              

### Cas bruité — Meilleur pourcentage à trois points

![Trace Logfire de la question 7](logfire/Logfire_question_7.png)

**Résultat :** malgré les fautes et les abréviations, les deux
joueurs attendus sont correctement identifiés à 100 %.
La précision « une seule tentative chacun » est absente.

**Contextes récupérés :** les cinq passages FAISS ne permettent
pas d’établir le classement. Le résultat SQL fournit les cinq
joueurs et leurs pourcentages, correctement repris dans le tableau.

**Réponse :** elle répond à l’intention de la question sans demander
de reformulation. Elle ajoute cependant une proposition de liens
non demandée et ne contextualise pas les 100 % par le nombre
de tentatives.

**Diagnostic :** la formulation bruitée est correctement comprise.
La requête utilise three_point_pct et un tri décroissant.
Le classement correspond à celui obtenu pour la question bien
orthographiée, mais three_points_attempted n’est pas sélectionné.

**Observation Logfire et tool SQL :** la trace confirme un seul
appel au tool SQL et deux appels au modèle. La recherche FAISS
dure 287 ms, le tool SQL environ 1,33 seconde et le pipeline
environ 4,20 secondes.

**Métriques :** la fidélité de 0,86 et la pertinence de 0,71
indiquent une réponse largement soutenue et pertinente.
La précision des contextes est de 0,17. L’exactitude factuelle
de 0,00 contraste avec les noms et pourcentages corrects :
l’omission des tentatives est réelle, mais les jugements détaillés
seraient nécessaires pour expliquer ce score.

**Pistes d’amélioration à tester :**
- Récupérer le nombre de tentatives pour contextualiser les pourcentages.
- Supprimer les propositions de liens lorsqu’ils ne sont pas demandés.
- Réduire les passages FAISS inutiles pour les classements statistiques.
- Étendre les tests à d’autres formulations bruitées pour vérifier
  que cette bonne compréhension se maintient.

In [15]:
row = results_V03.loc[
    results_V03["question"].str.contains(
        "Toulouse", case=False, na=False
    )
].iloc[0]

print("\nQUESTION :")
print(row["question"])

print("\nRÉPONSE ATTENDUE :")
print(row["reference"])

print("\nRÉPONSE OBTENUE :")
print(row["answer"])

contexts = ast.literal_eval(row["retrieved_contexts"])

for i, context in enumerate(contexts, start=1):
    print(f"\n{'-' * 30} CONTEXTE {i} {'-' * 30}\n")
    print(context)


QUESTION :
Quel temps fera-t-il demain à Toulouse ?

RÉPONSE ATTENDUE :
Je ne dispose pas de données météorologiques permettant de répondre à cette question.

RÉPONSE OBTENUE :
Je ne peux pas répondre à cette question, car elle ne concerne pas les statistiques NBA de la saison 2024-25 ni les données disponibles dans les contextes fournis.

------------------------------ CONTEXTE 1 ------------------------------

34                                                 MEM                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN
35                                                 NaN                      NaN                          NaN                               NaN                                          NaN                                         NaN                NaN                               NaN
36           

### Cas hors périmètre — Météo à Toulouse

![Trace Logfire de la question 8](logfire/Logfire_question_8.png)

**Résultat :** l’agent refuse correctement de fournir une prévision
météorologique. Aucune information météo n’est inventée.

**Contextes récupérés :** les cinq passages sont hors sujet.
Certains contiennent principalement des cellules vides, deux
sont identiques et aucun ne fournit de données météorologiques.

**Réponse :** le refus est adapté et cohérent avec la réponse
attendue. Sa justification pourrait être plus directe :
« Je ne dispose pas de données météorologiques. »
Le périmètre annoncé est trop restrictif, puisque l’assistant
traite aussi les commentaires des supporters.

**Diagnostic :** le respect du périmètre fonctionne dans la réponse
finale. Cependant, une recherche documentaire est effectuée
pour une question sans rapport avec les données disponibles.

**Observation Logfire et tool SQL :** la trace confirme une recherche
FAISS de 304 ms et un seul appel au modèle de 564 ms,
sans appel au tool SQL. Le pipeline dure environ 886 ms.
L’absence d’appel SQL est adaptée ; la recherche FAISS pourrait
être évitée par une détection préalable du hors périmètre.

**Métriques :** la pertinence et la précision des contextes sont
nulles, la fidélité vaut 0,60 et l’exactitude factuelle 0,33.
Ces scores ne suffisent pas à qualifier le refus d’échec :
l’évaluation humaine confirme un comportement adapté.
Ce cas doit aussi être évalué sur la capacité à refuser
sans inventer de réponse.

**Pistes d’amélioration à tester :**
- Détecter les questions hors périmètre avant la recherche FAISS.
- Formuler un refus court, centré sur les données indisponibles.
- Décrire le périmètre comme les statistiques NBA et les commentaires
  des supporters.
- Évaluer séparément les refus justifiés dans la grille humaine.

### Conclusion générale — Évaluation de la V03

L’analyse des huit questions montre que le tool SQL fournit des
résultats fiables pour les questions statistiques de ce jeu de test.
Les joueurs, les valeurs et les classements obtenus correspondent
aux éléments attendus. Le filtre des 100 tentatives est correctement
appliqué et la question comportant des fautes est bien comprise.

Les réponses restent parfois incomplètes : le nombre de tentatives
n’est pas précisé pour les pourcentages à trois points et l’écart
de 70 rebonds n’est pas explicité dans la comparaison. Des ajouts
inutiles subsistent également, notamment les propositions de liens
et l’affirmation non justifiée qu’une URL est indisponible.

**La recherche documentaire constitue la principale limite observée.**
Les passages FAISS sont souvent peu utiles pour les statistiques.
Pour les commentaires des supporters, ils sont soit hors sujet,
soit concentrés sur un seul fil Reddit. Ils ne permettent donc
pas toujours de couvrir les débats attendus. Un classement global
des joueurs par fréquence de mention nécessite également un
comptage du corpus, que la recherche de cinq extraits ne garantit pas.

**Logfire confirme une utilisation adaptée du tool SQL :**
il est appelé pour les cinq questions statistiques, mais pas pour
les commentaires ou la météo. Un appel SQL redondant est observé
sur une question. Les durées varient d’environ 0,89 à 29 secondes ;
les exécutions les plus lentes sont principalement dominées
par les appels au modèle.

**Les métriques RAGAS doivent être croisées avec l’analyse humaine.**
Certains scores d’exactitude factuelle sont faibles malgré des
noms et des valeurs corrects. À l’inverse, un score de 1,00 ne
signale pas toujours une omission dans la réponse. Deux scores
de fidélité sont manquants à cause d’erreurs du juge.
Le refus de répondre à la météo est adapté malgré des scores faibles.

La V03 présente donc des résultats statistiques convaincants sur
les cas testés, mais conserve des limites de recherche documentaire,
de complétude et de formulation. La comparaison avec la V01 reste
nécessaire pour mesurer précisément l’amélioration ; ces huit cas
ne suffisent pas à généraliser la fiabilité à toutes les questions.

**Priorités d’amélioration à tester :**
- Adapter les sources à la question : SQL pour les statistiques,
  documents Reddit pour les commentaires.
- Diversifier et nettoyer les passages documentaires récupérés.
- Compléter les réponses avec les tentatives ou les écarts utiles.
- Supprimer les remarques sur les liens lorsqu’ils ne sont pas demandés
  et éviter de déclarer absente une donnée non récupérée.
- Clarifier les incohérences du dictionnaire Excel et prévoir
  un comptage pour les questions de fréquence.
- Éviter les appels redondants et détecter le hors périmètre
  avant la recherche.

## Comparaison V01 / V03 — Effet de l’intégration du tool SQL

Les mêmes huit questions ont été utilisées pour les deux versions.
La comparaison porte sur l’exactitude des réponses, leur complétude
et leur justification par les données disponibles.

### Comparaison des réponses par cas

| Cas | V01 | V03 | Évolution observée |
|---|---|---|---|
| Joueurs les plus mentionnés | Classement incorrect, accompagné d’informations inventées. | Abstention face à des contextes insuffisants. | Moins d’inventions, mais la question reste sans réponse. |
| Principaux sujets de débat | Quelques thèmes corrects, mais plusieurs omissions et ajouts non étayés. | Plusieurs thèmes soutenus par les extraits, mais couverture toujours incomplète. | Meilleure fidélité aux extraits ; diversité documentaire encore insuffisante. |
| Meilleur pourcentage à trois points | Joueurs et pourcentages incorrects. | Alondes Williams et Skal Labissiere correctement identifiés à 100 %. | Amélioration nette ; le nombre de tentatives manque. |
| Meilleur pourcentage avec au moins 100 tentatives | Reggie Miller cité à tort avec 43,4 %. | Seth Curry correctement identifié à 45,6 %, avec le filtre SQL demandé. | Amélioration nette ; les 184 tentatives sont omises et la remarque sur l’URL est injustifiée. |
| Cinq meilleurs marqueurs | Classement incorrect et confusion entre totaux et moyennes. | Les cinq joueurs, les totaux et l’ordre sont corrects. | Réponse entièrement conforme à la référence. |
| Comparaison des rebonds | Totaux inventés et conclusion inversée. | Totaux corrects : 380 et 450 rebonds. | Amélioration nette ; l’écart de 70 rebonds reste implicite. |
| Question avec fautes | Intention comprise, mais classement incorrect. | Intention comprise et classement correct. | Compréhension maintenue et exactitude améliorée. |
| Question météo | Refus suivi de développements inutiles et non vérifiés. | Refus bref, sans prévision inventée. | Meilleur respect du périmètre et réponse plus concise. |

### Comparaison des métriques RAGAS

| Métrique | Moyenne V01 | Moyenne V03 | Évolution |
|---|---:|---:|---|
| Faithfulness | 0,26 | 0,85 | Forte hausse, mais seulement 6 scores disponibles en V03 contre 8 en V01. |
| Context precision | 0,07 | 0,19 | Hausse limitée ; de nombreux passages FAISS restent peu utiles. |
| Response relevancy | 0,65 | 0,60 | Légère baisse globale, avec 7 scores disponibles en V01 contre 8 en V03. |
| Factual correctness | 0,35 | 0,35 | Moyenne presque inchangée malgré des progrès numériques visibles. |

Ces moyennes ne suffisent pas à résumer l’évolution du système.

La pertinence augmente sur les cas disposant de scores dans les
deux versions, sauf pour la question des joueurs les plus mentionnés :
la V03 s’abstient, alors que la V01 produisait une réponse thématiquement
pertinente mais incorrecte. La baisse globale ne signifie donc pas
une dégradation générale des réponses.

L’exactitude factuelle illustre également les limites du juge :
le classement incorrect des joueurs mentionnés obtenait 0,80 en V01,
tandis que certaines réponses statistiques correctes obtiennent
0,00 en V03. Les causes précises nécessiteraient les jugements
détaillés de RAGAS.

Enfin, la hausse de fidélité accompagne une modification des preuves
transmises à l’évaluateur : la V03 inclut les résultats SQL dans
retrieved_contexts. Elle reflète donc à la fois des réponses mieux
fondées et la disponibilité de ces preuves pour le juge.

### Améliorations confirmées

**Le principal progrès concerne les questions statistiques.**
Les cinq cas numériques ou comparatifs de la V01 produisaient
des résultats incorrects. En V03, les noms et les valeurs essentiels
sont corrects dans les cinq cas, même si quatre réponses omettent
une précision présente dans la référence.

Les requêtes SQL observées utilisent les colonnes adaptées,
appliquent les filtres et produisent les classements nécessaires.
Logfire confirme leur exécution réelle. Les réponses reposent
ainsi sur des résultats structurés plutôt que sur des extrapolations
à partir de quelques passages Excel.

**Les réponses sont également plus maîtrisées.**
Les longues digressions et les inventions relevées en V01 diminuent.
Le refus hors périmètre est plus concis et l’abstention remplace
un classement non justifié pour les mentions de joueurs.

### Limites qui persistent

- La recherche FAISS récupère encore des passages hors sujet,
  incomplets ou redondants.
- Les questions sur les commentaires restent insuffisamment couvertes.
- Certaines réponses omettent les tentatives ou les écarts utiles.
- Des remarques inutiles sur les liens subsistent.
- Les métriques automatiques divergent parfois de la vérification humaine.

### Conclusion

**La V03 améliore nettement l’exactitude des réponses statistiques
sur ce jeu de test.** L’intégration du tool SQL répond à une limite
majeure identifiée en V01 : la recherche de quelques extraits
ne suffisait pas pour filtrer, classer ou comparer les données.

L’amélioration des questions textuelles est plus limitée :
les réponses sont davantage maîtrisées, mais les preuves récupérées
restent insuffisantes pour couvrir l’ensemble des commentaires.

Ces résultats soutiennent l’intérêt de l’architecture hybride.
Ils ne permettent toutefois pas d’attribuer tous les progrès au
seul SQL, puisque le prompt a également évolué, ni de généraliser
la fiabilité du système au-delà des huit cas évalués.

### Priorités d’amélioration à tester

- Adapter la recherche à la source nécessaire : statistiques SQL
  ou commentaires Reddit.
- Nettoyer et diversifier les extraits documentaires.
- Ajouter les précisions utiles : tentatives, joueur en tête et écart.
- Supprimer les remarques non demandées sur les liens.
- Prévoir un comptage pour les questions de fréquence.
- Étendre le jeu de test et conserver une évaluation humaine
  identique pour les prochaines versions.